### ISSUE TITLE
Tables and appendices in annotations

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1263] opened 2019-11-10 19:55 UTC
I have been going through edited annotations for first release. Could we please settle on the following table/appendix format within texts of the essays:

Format for Tables and Appendices: text in table is 10-pt, single spaced. All tables have a disclaimer under the title in the following format: [10-pt times new roman type] (transcriptions and translations from XXXX version of Ms. Fr. 640).

I have already put all of mine in this format, and have reformatted a number of others, but if you could please check your own, that would be appreciated! Thanks.

**Comment by thuchacz** [comment] 2019-11-10 20:44
@njr2128  and I were discussing this on Thursday. We put this into the meeting notes as something to discuss together this week because there are a few issues to parse. But since you've brought it up, here are some things to think about first:

1. Do we need a caption-like titling for all tables that would precede and be outside of the table itself, as in:

**Table 1: References to bed ornamentation in Ms. Fr. 640**

Folio and Entry Title | Mention of Bed Decoration
-- | --
Fol. <6v>For stampings to embellish and encrust or cover the edges of mirrors, the tops of chests, or the friezes of bed valances | See title.
Fol. <7r>For gilding with gold color and tinsel | You can cover trunks, mirrors, valences & bedposts with colored velvet or satin, then apply the gilded stampings on top with strong glue.

**OR...** should a table title be the first row of a table inside the table itself with no captioning outside, as in:
<img width="704" alt="Screen Shot 2019-11-10 at 15 43 12" src="https://user-images.githubusercontent.com/23508994/68550442-d92e6a00-03d0-11ea-99b7-c9b7c8e7d91c.png">




2. Should the title row(s) of a table be bolded or include a light-grey fill?

3.  Should all tables at the end of an essay be treated as Appendices (as they are in Imitating Raw Nature) or are they Tables (as they are in Stucco for Molding)?

**Comment by ps2270** [comment] 2019-11-10 20:51
1. Since we already have the first option in existing essays--a caption-like titling for all tables that would precede and be outside of the table itself--let's go with that. Title of the table/appendix should be bolded
2. no bolding, no fill
3. they should be treated as they now appear in the completed annotations. Some are appendices b/c they are so long and/or can be read by the reader later (e.g., Cultivating Cures). Some are tables b/c they are immediately important to the text (e.g., Jiang, What is Stone?). For future annotation revisions, decide on case by case basis.

**Comment by njr2128** [comment] 2019-11-13 20:41
NO FINAL DECISIONS MADE on all formatting. 
However, CONFIRMED: 10pt, Times New Roman, single space, justified left.

ACTION ITEM:
@ps2270 @Pantagrueliste @TillmannTaape @thuchacz 
go back through each annotation assigned to you and note in **Annotations tracking sheet** in dedicated column "contains table"

**Comment by njr2128** [comment] 2019-11-15 18:17
UPDATE:
PHS making list of all tables in annotations.

Rendering: 
Tables in annotations - formatting
Not sure what the styling is
NJR to make experimental table in stucco-example
Go from there after Nick has implemented and team sees how the styling is handled

**Comment by njr2128** [comment] 2019-12-10 15:54
Superseded by #1304

**Closed by njr2128** 2019-12-10 15:54 UTC
Labels: annotation
