### ISSUE TITLE
wellformedness error in all_tl.xml 

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#1680] opened 2020-06-01 18:25 UTC
xmlstarlet gives this error: 
``` all_tl.xml:21.1: Extra content at the end of the document <div id="p001r_2" categories="lists">```

**Comment by tcatapano** [comment] 2020-06-01 18:58
This is likely caused by the lack of a root `<all>` element. See #1629

**Comment by gschare** [comment] 2020-08-27 20:54
Closed via #1629.

**Closed** 2020-08-27 20:54 UTC
Labels: bug, derivatives, markup, xml
