### ISSUE TITLE
txt version incomplete

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#1696] opened 2020-06-13 22:17 UTC
Only one third of tcn_162r_1 is reproduced in the text version of entries. This is affecting the results of my analyses. I suspect it's a problem with XSLT and I'm afraid more divs are affected...

> Pour la boutique
Il se peult colliger par le dire d’Herodote que la
navigation
des Portugais n’est pas nouvellement
par eulx inventée comme ils se
ventent. Au comancement du premier livre
intitule Clio, il dict
que les Phoeniciens venoient de la mer Rouge par
continuelles
navigations en la coste de Græce, principallement à
Argos, où ilz
portoient des marchandises d’Ægipte & d’Assyrie,
que communement
en six jours il avoient debité.
Navigation,
marchandise

**Comment by njr2128** [comment] 2020-06-15 20:08
@matthewkumar and @gschare, can you look at the parsing of update.py and see what is going on here?

**Comment by tcatapano** [comment] 2020-06-15 23:06
@matthewkumar @gschare the file is https://github.com/cu-mkp/m-k-manuscript-data/commits/master/ms-txt/tcn/tcn_p161r_preTEI.txt

**Comment by matthewkumar** [comment] 2020-06-17 21:19
Me and @gschare took a look at this and figured out that the issue is caused by div tags with no IDs. From what I understand, div tags are used exclusively to mark the beginning and end of entries, not blocks of text within one entry. These unlabeled div tags are processed as a separate, unidentified entry. 

So long as it doesn't cause any other problems, we believe that simply removing the unlabeled div tags and using the ab tags within them will solve the problem.

**Comment by thuchacz** [comment] 2020-06-17 21:24
There are a few instances in which empty `<div>`s were added to help hack rendering problems. This may be what you are encountering.

**Comment by Pantagrueliste** [comment] 2020-06-18 15:47
Can we fill those divs with an empty unicode character instead?

**Comment by Pantagrueliste** [comment] 2020-06-22 21:19
Solution: discard /entries/txt/ files and use the /ms-txt/ files instead.

**Comment by tcatapano** [comment] 2020-06-30 20:28
The derivative generating code is behaving properly. On 162r there are only two entries, each of which is being output in their entirety. There are, however, divs in between the two entries which are not entries (i.e., have no id) and are not parts of other entries. We're assuming this is the desired structure for the editors. @njr2128 is this correct? The content of those non-entry divs, however, is being output in the folio txt versions under ms-txt.

**Comment by njr2128** [comment] 2020-08-27 21:50
We (@tcatapano and @gschare and @njr2128) have identified the larger issue here: it is a content/editorial problem, NOT a coding or a parsing problem. We believe that in order to better align the marginal emphs with their corresponding main text, multiple (2-3) divs were introduced so that it was broken up, see:
https://github.com/cu-mkp/m-k-manuscript-data/blob/2e720fd443866a21322eb7c395dbfd5232f039a7/ms-xml/tc/tc_p162r_preTEI.xml#L30-L63

![image](https://user-images.githubusercontent.com/14779727/91497560-36c27300-e88c-11ea-98e7-7b56c8781730.png)

## problem: because the first div of `<div id="p162r_1">` has now been closed in order to open the new divs that separate the emphs, these text blocks are now no longer associated with any entry (and have no div id). However, because they semantically belong to p162r_1, the text of this folio has changed in meaning. We have essentially said that these blocks of text do not belong with any other text and are not distinct entries themselves, which goes against our encoding policies. Normally, these would have "part" attributes.

Downstream consequences other than meaning include entry-metadata extraction and entries-txt and entries-xml (the text inside the unassigned divs is completely **omitted**). 

In order to remedy this, we need to understand why these additional divs are in place and why the "part" attribute is not used. We think it is because of rendering solutions put in place by @thuchacz. Can you confirm, @thuchacz? Otherwise, I will try to add "part" tags and see what happens to the rendering in edition-dev and then consult with PHS.

**Comment by njr2128** [comment] 2020-10-29 18:54
last comment moved to 162r. Otherwise, manuscript-object handles everything correctly

**Closed by njr2128** 2020-10-29 18:54 UTC
Labels: bug, derivatives
